# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

env:
- name: "APP_PORT"
  value: "7070"

image:
  repository: wooferius/demo
  # Overrides the image tag whose default is the chart appVersion.
  tag: gin-server@sha256:2707e57d12003510720f1c6fada9575a3606a6f3e486bc6b84e5d33e2ed6d563

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 7070

livenessProbe:
  httpGet:
    path: /management/liveness
    port: http

readinessProbe:
  httpGet:
    path: /management/readiness
    port: http

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
